apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: sandbox
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenbachtoann/TechTrends
    targetRevision: HEAD
    path: project/helm
    helm:
      valueFiles:
        - values-prod.yml
      releaseName: techtrends-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true